// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: go.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderServer  string                 `protobuf:"bytes,1,opt,name=sender_server,json=senderServer,proto3" json:"sender_server,omitempty"`
	OriginNick    string                 `protobuf:"bytes,2,opt,name=origin_nick,json=originNick,proto3" json:"origin_nick,omitempty"`
	OriginUser    string                 `protobuf:"bytes,3,opt,name=origin_user,json=originUser,proto3" json:"origin_user,omitempty"`
	OriginHost    string                 `protobuf:"bytes,4,opt,name=origin_host,json=originHost,proto3" json:"origin_host,omitempty"`
	Command       string                 `protobuf:"bytes,5,opt,name=command,proto3" json:"command,omitempty"`
	Params        []string               `protobuf:"bytes,6,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageRequest) Reset() {
	*x = MessageRequest{}
	mi := &file_go_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageRequest) ProtoMessage() {}

func (x *MessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageRequest.ProtoReflect.Descriptor instead.
func (*MessageRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{0}
}

func (x *MessageRequest) GetSenderServer() string {
	if x != nil {
		return x.SenderServer
	}
	return ""
}

func (x *MessageRequest) GetOriginNick() string {
	if x != nil {
		return x.OriginNick
	}
	return ""
}

func (x *MessageRequest) GetOriginUser() string {
	if x != nil {
		return x.OriginUser
	}
	return ""
}

func (x *MessageRequest) GetOriginHost() string {
	if x != nil {
		return x.OriginHost
	}
	return ""
}

func (x *MessageRequest) GetCommand() string {
	if x != nil {
		return x.Command
	}
	return ""
}

func (x *MessageRequest) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

type MessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageResponse) Reset() {
	*x = MessageResponse{}
	mi := &file_go_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageResponse) ProtoMessage() {}

func (x *MessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageResponse.ProtoReflect.Descriptor instead.
func (*MessageResponse) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{1}
}

func (x *MessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MessageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SyncRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderServer  string                 `protobuf:"bytes,1,opt,name=sender_server,json=senderServer,proto3" json:"sender_server,omitempty"`
	Channels      []*ChannelInfo         `protobuf:"bytes,2,rep,name=channels,proto3" json:"channels,omitempty"`
	Clients       []*ClientDetail        `protobuf:"bytes,3,rep,name=clients,proto3" json:"clients,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncRequest) Reset() {
	*x = SyncRequest{}
	mi := &file_go_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncRequest) ProtoMessage() {}

func (x *SyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncRequest.ProtoReflect.Descriptor instead.
func (*SyncRequest) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{2}
}

func (x *SyncRequest) GetSenderServer() string {
	if x != nil {
		return x.SenderServer
	}
	return ""
}

func (x *SyncRequest) GetChannels() []*ChannelInfo {
	if x != nil {
		return x.Channels
	}
	return nil
}

func (x *SyncRequest) GetClients() []*ClientDetail {
	if x != nil {
		return x.Clients
	}
	return nil
}

type SyncResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncResponse) Reset() {
	*x = SyncResponse{}
	mi := &file_go_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResponse) ProtoMessage() {}

func (x *SyncResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResponse.ProtoReflect.Descriptor instead.
func (*SyncResponse) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{3}
}

func (x *SyncResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SyncResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ClientInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Realname      string                 `protobuf:"bytes,4,opt,name=realname,proto3" json:"realname,omitempty"`
	IsOperator    bool                   `protobuf:"varint,5,opt,name=is_operator,json=isOperator,proto3" json:"is_operator,omitempty"`
	ServerName    string                 `protobuf:"bytes,6,opt,name=server_name,json=serverName,proto3" json:"server_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientInfo) Reset() {
	*x = ClientInfo{}
	mi := &file_go_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientInfo) ProtoMessage() {}

func (x *ClientInfo) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientInfo.ProtoReflect.Descriptor instead.
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{4}
}

func (x *ClientInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ClientInfo) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ClientInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ClientInfo) GetRealname() string {
	if x != nil {
		return x.Realname
	}
	return ""
}

func (x *ClientInfo) GetIsOperator() bool {
	if x != nil {
		return x.IsOperator
	}
	return false
}

func (x *ClientInfo) GetServerName() string {
	if x != nil {
		return x.ServerName
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_go_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{5}
}

func (x *StatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StatusResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ChannelInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Topic         string                 `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Modes         string                 `protobuf:"bytes,3,opt,name=modes,proto3" json:"modes,omitempty"`
	Clients       []string               `protobuf:"bytes,4,rep,name=clients,proto3" json:"clients,omitempty"`
	Operators     []string               `protobuf:"bytes,5,rep,name=operators,proto3" json:"operators,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelInfo) Reset() {
	*x = ChannelInfo{}
	mi := &file_go_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelInfo) ProtoMessage() {}

func (x *ChannelInfo) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelInfo.ProtoReflect.Descriptor instead.
func (*ChannelInfo) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{6}
}

func (x *ChannelInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ChannelInfo) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *ChannelInfo) GetModes() string {
	if x != nil {
		return x.Modes
	}
	return ""
}

func (x *ChannelInfo) GetClients() []string {
	if x != nil {
		return x.Clients
	}
	return nil
}

func (x *ChannelInfo) GetOperators() []string {
	if x != nil {
		return x.Operators
	}
	return nil
}

type ClientDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Realname      string                 `protobuf:"bytes,4,opt,name=realname,proto3" json:"realname,omitempty"`
	IsOperator    bool                   `protobuf:"varint,5,opt,name=is_operator,json=isOperator,proto3" json:"is_operator,omitempty"`
	Channels      []string               `protobuf:"bytes,6,rep,name=channels,proto3" json:"channels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientDetail) Reset() {
	*x = ClientDetail{}
	mi := &file_go_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientDetail) ProtoMessage() {}

func (x *ClientDetail) ProtoReflect() protoreflect.Message {
	mi := &file_go_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientDetail.ProtoReflect.Descriptor instead.
func (*ClientDetail) Descriptor() ([]byte, []int) {
	return file_go_proto_rawDescGZIP(), []int{7}
}

func (x *ClientDetail) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ClientDetail) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ClientDetail) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *ClientDetail) GetRealname() string {
	if x != nil {
		return x.Realname
	}
	return ""
}

func (x *ClientDetail) GetIsOperator() bool {
	if x != nil {
		return x.IsOperator
	}
	return false
}

func (x *ClientDetail) GetChannels() []string {
	if x != nil {
		return x.Channels
	}
	return nil
}

var File_go_proto protoreflect.FileDescriptor

const file_go_proto_rawDesc = "" +
	"\n" +
	"\bgo.proto\x12\x03irc\"\xca\x01\n" +
	"\x0eMessageRequest\x12#\n" +
	"\rsender_server\x18\x01 \x01(\tR\fsenderServer\x12\x1f\n" +
	"\vorigin_nick\x18\x02 \x01(\tR\n" +
	"originNick\x12\x1f\n" +
	"\vorigin_user\x18\x03 \x01(\tR\n" +
	"originUser\x12\x1f\n" +
	"\vorigin_host\x18\x04 \x01(\tR\n" +
	"originHost\x12\x18\n" +
	"\acommand\x18\x05 \x01(\tR\acommand\x12\x16\n" +
	"\x06params\x18\x06 \x03(\tR\x06params\"P\n" +
	"\x0fMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x8d\x01\n" +
	"\vSyncRequest\x12#\n" +
	"\rsender_server\x18\x01 \x01(\tR\fsenderServer\x12,\n" +
	"\bchannels\x18\x02 \x03(\v2\x10.irc.ChannelInfoR\bchannels\x12+\n" +
	"\aclients\x18\x03 \x03(\v2\x11.irc.ClientDetailR\aclients\"M\n" +
	"\fSyncResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xbe\x01\n" +
	"\n" +
	"ClientInfo\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1a\n" +
	"\brealname\x18\x04 \x01(\tR\brealname\x12\x1f\n" +
	"\vis_operator\x18\x05 \x01(\bR\n" +
	"isOperator\x12\x1f\n" +
	"\vserver_name\x18\x06 \x01(\tR\n" +
	"serverName\"O\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\x85\x01\n" +
	"\vChannelInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05topic\x18\x02 \x01(\tR\x05topic\x12\x14\n" +
	"\x05modes\x18\x03 \x01(\tR\x05modes\x12\x18\n" +
	"\aclients\x18\x04 \x03(\tR\aclients\x12\x1c\n" +
	"\toperators\x18\x05 \x03(\tR\toperators\"\xbb\x01\n" +
	"\fClientDetail\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x1a\n" +
	"\brealname\x18\x04 \x01(\tR\brealname\x12\x1f\n" +
	"\vis_operator\x18\x05 \x01(\bR\n" +
	"isOperator\x12\x1a\n" +
	"\bchannels\x18\x06 \x03(\tR\bchannels2\xe8\x01\n" +
	"\aIRCPeer\x12;\n" +
	"\fRelayMessage\x12\x13.irc.MessageRequest\x1a\x14.irc.MessageResponse\"\x00\x122\n" +
	"\tSyncState\x12\x10.irc.SyncRequest\x1a\x11.irc.SyncResponse\"\x00\x126\n" +
	"\fClientJoined\x12\x0f.irc.ClientInfo\x1a\x13.irc.StatusResponse\"\x00\x124\n" +
	"\n" +
	"ClientLeft\x12\x0f.irc.ClientInfo\x1a\x13.irc.StatusResponse\"\x00B$Z\"github.com/presbrey/pkg/ircd/protob\x06proto3"

var (
	file_go_proto_rawDescOnce sync.Once
	file_go_proto_rawDescData []byte
)

func file_go_proto_rawDescGZIP() []byte {
	file_go_proto_rawDescOnce.Do(func() {
		file_go_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_go_proto_rawDesc), len(file_go_proto_rawDesc)))
	})
	return file_go_proto_rawDescData
}

var file_go_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_go_proto_goTypes = []any{
	(*MessageRequest)(nil),  // 0: irc.MessageRequest
	(*MessageResponse)(nil), // 1: irc.MessageResponse
	(*SyncRequest)(nil),     // 2: irc.SyncRequest
	(*SyncResponse)(nil),    // 3: irc.SyncResponse
	(*ClientInfo)(nil),      // 4: irc.ClientInfo
	(*StatusResponse)(nil),  // 5: irc.StatusResponse
	(*ChannelInfo)(nil),     // 6: irc.ChannelInfo
	(*ClientDetail)(nil),    // 7: irc.ClientDetail
}
var file_go_proto_depIdxs = []int32{
	6, // 0: irc.SyncRequest.channels:type_name -> irc.ChannelInfo
	7, // 1: irc.SyncRequest.clients:type_name -> irc.ClientDetail
	0, // 2: irc.IRCPeer.RelayMessage:input_type -> irc.MessageRequest
	2, // 3: irc.IRCPeer.SyncState:input_type -> irc.SyncRequest
	4, // 4: irc.IRCPeer.ClientJoined:input_type -> irc.ClientInfo
	4, // 5: irc.IRCPeer.ClientLeft:input_type -> irc.ClientInfo
	1, // 6: irc.IRCPeer.RelayMessage:output_type -> irc.MessageResponse
	3, // 7: irc.IRCPeer.SyncState:output_type -> irc.SyncResponse
	5, // 8: irc.IRCPeer.ClientJoined:output_type -> irc.StatusResponse
	5, // 9: irc.IRCPeer.ClientLeft:output_type -> irc.StatusResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_go_proto_init() }
func file_go_proto_init() {
	if File_go_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_go_proto_rawDesc), len(file_go_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_go_proto_goTypes,
		DependencyIndexes: file_go_proto_depIdxs,
		MessageInfos:      file_go_proto_msgTypes,
	}.Build()
	File_go_proto = out.File
	file_go_proto_goTypes = nil
	file_go_proto_depIdxs = nil
}
