// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.29.3
// source: go.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IRCPeerClient is the client API for IRCPeer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IRCPeerClient interface {
	// Relay a message from one server to another
	RelayMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error)
	// Sync server state between peers
	SyncState(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error)
	// Notify a peer about a new client
	ClientJoined(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*StatusResponse, error)
	// Notify a peer about a client that left
	ClientLeft(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*StatusResponse, error)
}

type iRCPeerClient struct {
	cc grpc.ClientConnInterface
}

func NewIRCPeerClient(cc grpc.ClientConnInterface) IRCPeerClient {
	return &iRCPeerClient{cc}
}

func (c *iRCPeerClient) RelayMessage(ctx context.Context, in *MessageRequest, opts ...grpc.CallOption) (*MessageResponse, error) {
	out := new(MessageResponse)
	err := c.cc.Invoke(ctx, "/irc.IRCPeer/RelayMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iRCPeerClient) SyncState(ctx context.Context, in *SyncRequest, opts ...grpc.CallOption) (*SyncResponse, error) {
	out := new(SyncResponse)
	err := c.cc.Invoke(ctx, "/irc.IRCPeer/SyncState", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iRCPeerClient) ClientJoined(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/irc.IRCPeer/ClientJoined", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *iRCPeerClient) ClientLeft(ctx context.Context, in *ClientInfo, opts ...grpc.CallOption) (*StatusResponse, error) {
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, "/irc.IRCPeer/ClientLeft", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IRCPeerServer is the server API for IRCPeer service.
// All implementations must embed UnimplementedIRCPeerServer
// for forward compatibility
type IRCPeerServer interface {
	// Relay a message from one server to another
	RelayMessage(context.Context, *MessageRequest) (*MessageResponse, error)
	// Sync server state between peers
	SyncState(context.Context, *SyncRequest) (*SyncResponse, error)
	// Notify a peer about a new client
	ClientJoined(context.Context, *ClientInfo) (*StatusResponse, error)
	// Notify a peer about a client that left
	ClientLeft(context.Context, *ClientInfo) (*StatusResponse, error)
	mustEmbedUnimplementedIRCPeerServer()
}

// UnimplementedIRCPeerServer must be embedded to have forward compatible implementations.
type UnimplementedIRCPeerServer struct {
}

func (UnimplementedIRCPeerServer) RelayMessage(context.Context, *MessageRequest) (*MessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RelayMessage not implemented")
}
func (UnimplementedIRCPeerServer) SyncState(context.Context, *SyncRequest) (*SyncResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SyncState not implemented")
}
func (UnimplementedIRCPeerServer) ClientJoined(context.Context, *ClientInfo) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientJoined not implemented")
}
func (UnimplementedIRCPeerServer) ClientLeft(context.Context, *ClientInfo) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClientLeft not implemented")
}
func (UnimplementedIRCPeerServer) mustEmbedUnimplementedIRCPeerServer() {}

// UnsafeIRCPeerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IRCPeerServer will
// result in compilation errors.
type UnsafeIRCPeerServer interface {
	mustEmbedUnimplementedIRCPeerServer()
}

func RegisterIRCPeerServer(s grpc.ServiceRegistrar, srv IRCPeerServer) {
	s.RegisterService(&IRCPeer_ServiceDesc, srv)
}

func _IRCPeer_RelayMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IRCPeerServer).RelayMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/irc.IRCPeer/RelayMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IRCPeerServer).RelayMessage(ctx, req.(*MessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IRCPeer_SyncState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IRCPeerServer).SyncState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/irc.IRCPeer/SyncState",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IRCPeerServer).SyncState(ctx, req.(*SyncRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IRCPeer_ClientJoined_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IRCPeerServer).ClientJoined(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/irc.IRCPeer/ClientJoined",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IRCPeerServer).ClientJoined(ctx, req.(*ClientInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _IRCPeer_ClientLeft_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IRCPeerServer).ClientLeft(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/irc.IRCPeer/ClientLeft",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IRCPeerServer).ClientLeft(ctx, req.(*ClientInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// IRCPeer_ServiceDesc is the grpc.ServiceDesc for IRCPeer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IRCPeer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "irc.IRCPeer",
	HandlerType: (*IRCPeerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RelayMessage",
			Handler:    _IRCPeer_RelayMessage_Handler,
		},
		{
			MethodName: "SyncState",
			Handler:    _IRCPeer_SyncState_Handler,
		},
		{
			MethodName: "ClientJoined",
			Handler:    _IRCPeer_ClientJoined_Handler,
		},
		{
			MethodName: "ClientLeft",
			Handler:    _IRCPeer_ClientLeft_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go.proto",
}
