version: 2
updates:
  - package-ecosystem: gomod
    directories:
      - /
      - /base92/cli
      - /git-http-cache
    schedule:
      interval: weekly
    groups:
      go-dependencies:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /git-http-cache
    schedule:
      interval: weekly
